### ISSUE TITLE
add ping of player

### ISSUE THREAD

**Issue by razorfish-sl** [thibmo/PlayerAdministration#11]
Hi can you look at and include this patch

it adds a player ping on the player detail page, it is a snapshot when the page is opened so that it is not running a continual ping.

trapped for player disconnected

[0001-Added-ping.txt](https://github.com/thibmo/PlayerAdministration/files/8280022/0001-Added-ping.txt)
h

**Comment by thibmo** [comment]
You made a diff, just fork the repo, commit and push there, then do a pull request.
Working with patches like this kinda sucks TBH, because there is no good audit trail of who contributed what. :)

**Comment by razorfish-sl** [comment]
yep i can do that, just  I did not want  people contacting me for plugins or work...

**Comment by thibmo** [comment]
No worries, I just patched it for this enhancement. :)
I just like to give credit where credit is deserved. Pushing now.
