### ISSUE TITLE
Help Wounded

### ISSUE THREAD

**Issue by Mheetu** [thibmo/PlayerAdministration#4]
I'm going to hold off on creating new PRs until you complete your refactor... but another thing that might be useful is to add `if (player.IsWounded()) player.StopWounded();` to the `PlayerAdministrationHealUserCallback` method.

I feel like if someone is trying to heal a "wounded" (downed) player, it would be expected that they'd be helped up too.

Additionally, a new button "Help Wounded" that would heal for 0 could be added to the "Heal" row and the "Kill" button could be moved down to the "Hurt" row.

**Comment by thibmo** [comment]
Or perhaps "Heal Wounds" or something, sure.
I moved on quite a bit, I'll spend tonight on this as well with hope to round up the edits for now.

**Comment by thibmo** [comment]
Has been added. :)
