### ISSUE TITLE
Add confirmation to dangerous actions

### ISSUE THREAD

**Issue by AttilaBalla** [thibmo/PlayerAdministration#5]
Hello,

We just switched to your admintool and I accidentally managed to wipe BPs twice now due to 2 really inconvenient behaviors. 

The tool sometimes places the mouse cursor on the center of the screen, and it just so happens that the BP reset button is right there as well, so if for example I'm trying to teleport to a player and it doesn't work, when my mouse gets reset I end up wiping BPs instead.

Second major issue is that there is no confirmation message or warning dialog either, yet the BP reset and the inventory clear actions can cause serious issues if used by accident.

**Comment by thibmo** [comment]
1st issue : Not something I am able to fix, this is due to the slowness of the UI API. (Not a umod issue, a game issue.)

2nd issue : I could look into this, ~~though I believe the user should be careful with admin panels and not accidentally click on buttons, always double check.~~

**Comment by AttilaBalla** [comment]
Yeah I agree with that, however these 2 issues correlate, if the tool wouldn't move my mouse then it would be easier to avoid doing unintentional actions. Our previous tool didn't do this, so while i'm not familiar with how plugin development works, I'd say it's worth to investigate. 

Also the "Main" screen does not really provide any useful information so I suggest showing the "online players" tab when opening the tool. That's another minor but inconvenient issue that I have with it.

Btw I really appreciate the quick response and I'm happy that this is a tool that's still being developed, so I'm only trying to provide constructive feedback.

Thanks a lot :)

**Comment by thibmo** [comment]
All fine. :)
Plugin UI development is hellish for more complex "Community UI". The end result is a JSON string to the client RPC. what I could do is have some more constant/readonly objects rather then regenerating them each time. Or use a transparent background panel to parent the actual UI and just destroy the actual UI on each page switch, that way the `CursorEnabled` will stay enabled.

Not sure what other tool you used in the past, though.
The main tab at the moment just houses the "Ban by ID" input, indeed. Didn't really know where else to stuff it.

**Comment by thibmo** [comment]
Could you perhaps try the most recent commit and tell me if this is better?
I sadly didn't get the chance to test it yet.

**Comment by AttilaBalla** [comment]
Sure thing, what changes should we look out for?

**Comment by thibmo** [comment]
Mainly speed and the self-centering mouse cursor
