### ISSUE TITLE
Spectator mode

### ISSUE THREAD

**Issue by PEKKAch4KA** [thibmo/PlayerAdministration#9]
How to exit from spectator mode?

**Comment by thibmo** [comment]
Please read the provided README.md, it's in there twice.

![image](https://user-images.githubusercontent.com/12035362/118688454-5cbae980-b806-11eb-9923-0d53bbd2e182.png)
and
![image](https://user-images.githubusercontent.com/12035362/118688624-84aa4d00-b806-11eb-8d1b-9aca3069408b.png)

**Comment by PEKKAch4KA** [comment]
how to revive my character?

PS: kill doesn't help
